version:             1.3.0 
github:
  repo:              https://github.com/techgraphics/techgraphics.github.io

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Time Zone
timezone: Australia/Adelaide

# Produce an index for related posts
lsi: false

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Ruby Gems
# gems:
#  - jekyll-assets
#  - jekyll-html-pipeline
#  - jekyll-sitemap
#  - autoprefixer-rails

# Site specific settings
url:                 http://techgraphics.github.io
baseurl:             /

# Post settings
paginate:            3
paginate_path: "/posts/page:num/"

# Collections
collections: 
- glossary
- resources
- skills 
